### ISSUE TITLE
Failing to delete realtekservice.inf causes an endless loop

### ISSUE THREAD

**Issue by CrimsonRunner** [pal1000/Realtek-UAD-generic#63]
![image](https://user-images.githubusercontent.com/40888249/103290157-8f984880-49f1-11eb-9bc8-254fbd0145dd.png)

I first used the latest version of the provided setup and the setup ran fine. I discovered my Realtek service wasn't able to start and read somewhere it might be related to the driver version so I decided to go with an older version of the setup 6.0.8874 but when I ran that I encountered the problem shown in the picture. Since it's an endless loop, I obviously closed it. Tried running the new version again and that ended in a loop as well. Restarting in safe mode did nothing. Restarting normally triggered the setup to run again. When prompted to manage myself, updates of codec, extension and  software components selecting Y force updates successfully, selecting N results in an endless loop.

I went and manually deleted the folders related to realtek drivers from the driverStore but this did not resolve the issue. As far as I can tell the driver it's saying is in use does not even exist.

I used the microsoft troubleshooter to restore sound.

**Comment by connnorturner** [comment]
Hi, this is very similar to the issue I'm having, did this occur after a first-time setup of the realtek drivers, or did you re-install the?

**Comment by CrimsonRunner** [comment]
Given that I had previously ran a newer version of the setup, they've been reinstalled.

**Comment by pal1000** [comment]
Grab [Driver store explorer](https://github.com/lostindark/DriverStoreExplorer/releases) then remove `realtekservice.inf` using force delete option. It probably remained tied to a driver that's not installed anymore.

**Comment by CrimsonRunner** [comment]
As I mentioned, I've deleted all non-ethernet realtek drivers from the driverStore folder. I did this manually because Driver store explorer was unable to delete them, even when using force delete.

Uploaded the driver list in a csv file, as provided by the driver store explorer. It's in a zip because github wouldn't accept a .csv file


[drivers.zip](https://github.com/pal1000/Realtek-UAD-generic/files/5758868/drivers.zip)

**Comment by pal1000** [comment]
Delete the DTS branded drivers and that should solve the problem. DTS is an audio 3rd party component and it probably keeps the service running.

**Comment by CrimsonRunner** [comment]
I deleted all 3 of the DTS drivers but the setup is still unable to delete the inf file.

**Comment by pal1000** [comment]
Force delete it with Driver store explorer. It probably remained stuck in use.

**Comment by CrimsonRunner** [comment]
The driverstore does not display any Realtek drivers, except for the network ones, for me to delete.
I removed oem12, 14 and 58 .inf and .PNF from Windows\INF and now I receive a new error. I tried reinstalling the official 2.82 realtek drivers in an attempt to restore any pathing but the error persistent.

![изображение](https://user-images.githubusercontent.com/40888249/103832073-26b26f80-5086-11eb-9eab-b1b3e62988f9.png)

**Comment by pal1000** [comment]
Use driver store explorer to add `realtekservice.inf` back using add driver option. You should find it in `Realtek-UAD-generic\Win64\Realtek\RealtekService_315`. Then try setup again.

**Comment by CrimsonRunner** [comment]
added the realtekservice and then it had an issue with the realtekapo. Closed it again, added both from the driver store explorer and the setup completed successfully now.

**Comment by albertopasqualetto** [comment]
> added the realtekservice and then it had an issue with the realtekapo. Closed it again, added both from the driver store explorer and the setup completed successfully now.

I also needed to check the install checkbox before adding the driver.
